service: EmailSQSTrigerr
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: index.handler
    events: 
      - sqs: arn:aws:sqs:us-east-1:679527650604:EmailSMSQueue